name: search_map_place
description: A Search Widget that allows users to search for a place while getting autocompletion feedback.
version: 0.1.0+2
author: Lucas Bernardi <lucasbernardi.23@gmail.com>
homepage: https://github.com/Bernardi23/search_map_place

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: 
    git:
      url: git://github.com/Eimji/plugins
      path: packages/google_maps_flutter  
  #  path: /home/patrick/DATA/Github/Flutter_packages/plugins/packages/google_maps_flutter
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
